language: java
install: true

jdk:
  - openjdk8

matrix:
  include:
    - env: TEST=1
      script: ./gradlew tasks -s
    - env: TEST=2
      script: ./gradlew jacocoTestReport -s
  fast_finish: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
