language: java
install: true

jdk:
  - openjdk8

matrix:
  include:
    - env: TEST=1
      script: ./gradlew tasks -all
    - env: TEST=2
      script: ./gradlew cleanAll -s --warning-mode all
      #script: gradle run test_me jacoco
  fast_finish: true
