language: java
install: true

jdk:
  - openjdk8

matrix:
  include:
    - env: TEST=1
      #script: ./gradlew build
      script: ./gradlew lint
    - env: TEST=2
      script: ./gradlew clean
      #script: gradle run test_me jacoco
    - env: TEST=3
      script: ./gradlew test
  allow_failures:
    - language: generic
  fast_finish: true

# https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html
