language: java
install: true

jdk:
  - openjdk8

matrix:
  include:
    - env: TEST=1
      #script: ./gradlew build
      script: ./gradlew TryToErrorOut
    - env: TEST=2
      script: ./gradlew cleanAll -s --warning-mode all
      #script: gradle run test_me jacoco
  fast_finish: true
